language: node_js
sudo: false

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "node"

matrix:
  allow_failures:
    - node_js: "node"

before_script:
  - export HARMONY_OPTS=$(node --v8-options | grep --only-matching -- '--harmony_generators')

after_script:
  npm run coveralls
